// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// harmonic_function_cpp
arma::mat harmonic_function_cpp(const arma::mat& W, const arma::mat& Y);
RcppExport SEXP RSSL_harmonic_function_cpp(SEXP WSEXP, SEXP YSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP );
        Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP );
        arma::mat __result = harmonic_function_cpp(W, Y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
