#' Loss of a classifier or regression function
#' 
#' @param object TODO
#' @param y Vector with true classes of the test data
#' @param newdata data.frame object with test data
#' @param ... additional parameters
#' @return numeric of the total loss on the test data
#' 
#' @export
#' @docType methods
#' @rdname loss-methods
setGeneric("loss",function(object, ...) {standardGeneric("loss")})

#' Loss of a classifier or regression function evaluated on partial labels
#' 
#' @param object TODO
#' @param ... additional parameters
#' @return numeric of the total loss on the test data
#' 
#' @export
#' @docType methods
#' @rdname losspart-methods
setGeneric("losspart",function(object, ...) {standardGeneric("losspart")})

#' LogsumLoss of a classifier or regression function
#' 
#' @param object Classifier or Regression object
#' @param ... Additional parameters
#' 
#' @export
#' @docType methods
#' @rdname losslogsum-methods
setGeneric("losslogsum",function(object, ...) {standardGeneric("losslogsum")})

#' Class Posteriors of a classifier
#' 
#' @param object Classifier or Regression object
#' @param ... Additional parameters
#' 
#' @export
#' @docType methods
#' @rdname posterior-methods
setGeneric("posterior",function(object, ...) {standardGeneric("posterior")})

#' Decision values returned by a classifier for a set of objects
#' 
#' Returns decision values of a classifier
#' 
#' @param object Classifier object
#' @param newdata new data to classify
#' 
#' @export
#' @docType methods
#' @rdname decisionvalues-methods
setGeneric("decisionvalues",function(object, newdata)
  standardGeneric("decisionvalues")
)

#' Decision Boundary plot of a classifier
#' 
#' @param object object to plot
#' @param p ggplot object of classification problem generated by clplot
#' @param ... Additional options
#' 
#' @export
#' @docType methods
#' @rdname boundaryplot-methods
setGeneric("boundaryplot",function(object,...) {standardGeneric("boundaryplot")})


#' Show RSSL classifier
#' @name rssl-formatting
#' @param object classifier
NULL

#' Predict using RSSL classifier
#' @name rssl-predict
#' @param object classifier
#' @param newdata objects to generate predictions for
#' @param ... Other arguments
#' @param probs Whether probabilities should be returned
NULL