#' Loss of a classifier or regression function
#' 
#' @param object TODO
#' @param y Vector with true classes of the test data
#' @param newdata data.frame object with test data
#' @param ... additional parameters
#' @return numeric of the total loss on the test data
#' 
#' @export
#' @docType methods
#' @rdname loss-methods
setGeneric("loss",function(object, ...) {standardGeneric("loss")})

#' Loss of a classifier or regression function evaluated on partial labels
#' 
#' @param object TODO
#' @param ... additional parameters
#' @return numeric of the total loss on the test data
#' 
#' @export
#' @docType methods
#' @rdname losspart-methods
setGeneric("losspart",function(object, ...) {standardGeneric("losspart")})

#' LogsumLoss of a classifier or regression function
#' 
#' @param object Classifier or Regression object
#' @param ... Additional parameters
#' 
#' @export
#' @docType methods
#' @rdname losslogsum-methods
setGeneric("losslogsum",function(object, ...) {standardGeneric("losslogsum")})

#' Predictions of a classifier or regression function
#' 
#' @param object Classification or Regression object
#' @param newdata new data to predict
#' @param probs logical; Whether probabilities should be returned
#' @param ... Additional parameters
#' 
#' @export
#' @docType methods
#' @rdname predict-methods
setGeneric("predict",function(object, ...) {standardGeneric("predict")})

#' Class Posteriors of a classifier
#' 
#' @param object Classifier or Regression object
#' @param ... Additional parameters
#' 
#' @export
#' @docType methods
#' @rdname posterior-methods
setGeneric("posterior",function(object, ...) {standardGeneric("posterior")})

#' @export
setGeneric("decisionvalues",function(object, newdata)
  standardGeneric("decisionvalues")
)

#' Plot function
#' 
#' @param x Classifier or Regression object
#' @param y TODO
#' @param ... Additional parameters
#' 
#' @export
#' @docType methods
#' @rdname plot-methods
setGeneric("plot",function(x, y, ...) {standardGeneric("plot")})

#' Decision Boundary plot of a classifier
#' 
#' @param object object to plot
#' @param p ggplot object of classification problem generated by clplot
#' @param ... Additional options
#' 
#' @export
#' @docType methods
#' @rdname boundaryplot-methods
setGeneric("boundaryplot",function(object,...) {standardGeneric("boundaryplot")})
