# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

harmonic_function_cpp <- function(W, Y) {
    .Call(`_RSSL_harmonic_function_cpp`, W, Y)
}

svmlin_rcpp <- function(X, y, l, algorithm, lambda, lambda_u, max_switch, pos_frac, Cp, Cn, costs, verbose) {
    .Call(`_RSSL_svmlin_rcpp`, X, y, l, algorithm, lambda, lambda_u, max_switch, pos_frac, Cp, Cn, costs, verbose)
}

rowMax <- function(X) {
    .Call(`_RSSL_rowMax`, X)
}

rowMax2 <- function(X) {
    .Call(`_RSSL_rowMax2`, X)
}

which_rowMax <- function(X) {
    .Call(`_RSSL_which_rowMax`, X)
}

which_rowMax2 <- function(X) {
    .Call(`_RSSL_which_rowMax2`, X)
}

sort_matrix <- function(X) {
    .Call(`_RSSL_sort_matrix`, X)
}

rowwise_addition <- function(A, x) {
    .Call(`_RSSL_rowwise_addition`, A, x)
}

factor_to_dummy_cpp <- function(y, c) {
    .Call(`_RSSL_factor_to_dummy_cpp`, y, c)
}

