# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

harmonic_function_cpp <- function(W, Y) {
    .Call('RSSL_harmonic_function_cpp', PACKAGE = 'RSSL', W, Y)
}

svmlin_rcpp <- function(X, y, l, algorithm, lambda, lambda_u, max_switch, pos_frac, Cp, Cn, costs, verbose) {
    .Call('RSSL_svmlin_rcpp', PACKAGE = 'RSSL', X, y, l, algorithm, lambda, lambda_u, max_switch, pos_frac, Cp, Cn, costs, verbose)
}

